### ISSUE TITLE
idea: gitgnore

### ISSUE THREAD

**Issue by JanuszJakubiak** [goorkamateusz/praca-dyplomowa-szablon#1]
Jeśli folder szablonu ma być wykorzystywany bezpośrednio do pisania pracy, może warto dodać wpisy do .gitignore według:
https://github.com/github/gitignore/blob/main/TeX.gitignore
(jeśli nie całość, to przynajmniej te z linii 1-13, 27-33)

**Comment by goorkamateusz** [comment]
Jak najbardziej, mój .gitignore działałby tylko dla vscode z wskazanymi wtyczkami i konfiguracją.
